name: jawline_fitness
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.3
  animated_splash_screen: ^1.3.0
  email_validator: ^2.1.17
  alarm: ^1.1.5
  permission_handler: ^10.4.3
  infinite_listview: ^1.1.0
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  shared_preferences: ^2.2.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
