name: jawline_fitness
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.3
  animated_splash_screen: ^1.3.0
  email_validator: ^2.1.17
  alarm: ^1.1.5
  permission_handler: ^10.4.3
  infinite_listview: ^1.1.0
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_local_notifications: ^15.1.1
  flutter_tts: ^3.8.3



  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Black.ttf
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-ExtraBold.ttf
        - asset: fonts/Raleway-SemiBold.ttf
          style: italic
  assets: 
    - assets/
